### ISSUE TITLE
Speaking for a friend, but her files are getting corrupt and nothing is working to fix it

### ISSUE THREAD

**Issue by ShadowWind87** [LordDeatHunter/Musica#1]

**Comment by LordDeatHunter** [comment]
Server or client? Any other mods installed? Any errors or logs? Are you sure it's this mod?

**Comment by ShadowWind87** [comment]
yes, she is trying to play an origins server, its all fine with me and tons of other people, but this mod specifically is causing a problem and being corrupt

**Comment by ShadowWind87** [comment]
no other clients that i know of

**Comment by ShadowWind87** [comment]
![image](https://user-images.githubusercontent.com/83791608/117374359-09a67580-ae9b-11eb-94d9-9d4ef31d75ab.png)
this is what it is saying, and this
![Uploading image.png…]()

**Comment by LordDeatHunter** [comment]
Looks like an unfinished download?

**Comment by K0-RR** [comment]
Probably can be closed by now, just a reminder.
